### ISSUE TITLE
Linkedin and Github icon links disappear when blog page is visited

### ISSUE THREAD

**Issue by finite-simple-group-of-order-two** [siddhant-afk/portfolio#1]
Platform: Windows 10: WSL2 Ubuntu 20.04
Browser: Microsoft Edge Version 95.0.1020.44 (Official build) (64-bit)
Python version: 3.8.10
Django version: 3.2.6

Issue:
The buttons with the github and linkedin icons, next to the "blog" button on the navbar; in the projects page, disappear when the Blog page is opened

Reproduction steps:
1. Run server by opening a terminal in the outermost dir and typing in `python3 manage.py runserver`
2.  Open home page
3. Click the "Blog" button on the navbar

**Comment by siddhant-afk** [comment]
Dear Mr. Ashutosh. Thank you for the review and raising an issue. I'd like to apologize for any grievance you have faced while the navigating my website. You see, the Github and Linkedin Icons disappear on visiting the Blog page because they are simply not there. I as a normal human being did not think it was necessary for them to show up everywhere. I hope that solves the issue. Thank you for your concern.
